# Generated by Django 4.2.23 on 2025-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='영화 제목')),
                ('release_year', models.IntegerField(verbose_name='개봉 년도')),
                ('genre', models.CharField(choices=[('Action', '액션'), ('Comedy', '코미디'), ('Drama', '드라마'), ('Horror', '공포'), ('Romance', '로맨스'), ('SF', 'SF'), ('Thriller', '스릴러')], max_length=10, verbose_name='장르')),
                ('rating', models.FloatField(verbose_name='별점')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actors', models.CharField(max_length=200, verbose_name='주연')),
                ('running_time', models.IntegerField(verbose_name='러닝타임 (분)')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
